### ISSUE TITLE
BodyImage Component

### ISSUE THREAD

**Issue by JamieB-gu** [guardian/image-rendering#8]
Create a `BodyImage` component modelled on the same from Apps-Rendering.

**Comment by mxdvl** [comment]
We could use closing keywords when creating PRs to [automatically link an issue][closing-keywords]:

[closing-keywords]: https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword

> ### Linking a pull request to an issue using a keyword
> You can link a pull request to an issue by using a supported keyword in the pull request's description.
> - close
> - closes
> - closed
> - fix
> - fixes
> - fixed
> - resolve
> - resolves
> - resolved
> 
> The syntax for closing keywords depends on whether the issue is in the same repository as the pull request.

**Comment by mxdvl** [comment]
We could use closing keywords when creating PRs to [automatically link an issue][closing-keywords]:

[closing-keywords]: https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword

> ### Linking a pull request to an issue using a keyword
> You can link a pull request to an issue by using a supported keyword in the pull request's description.
> - close
> - closes
> - closed
> - fix
> - fixes
> - fixed
> - resolve
> - resolves
> - resolved
> 
> The syntax for closing keywords depends on whether the issue is in the same repository as the pull request.
